
package br.eti.sen.endereco.wscorreios;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebFault(name = "SigepClienteException", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class SigepClienteException extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private String faultInfo;

    // MÉTODOS PÚBLICOS

    /**
     *
     * @param faultInfo
     * @param message
     */
    public SigepClienteException(String message, String faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SigepClienteException(String message, String faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return returns fault bean: {@link String}
     */
    public String getFaultInfo() {
        return faultInfo;
    }

}
